//! Keyboard input types.
//!
//! Full keymap + state handling lands in #10 (Phase 1). The types
//! exposed here are the public surface consumers see — keep
//! implementation details (xkbcommon contexts, modifier-mask bits)
//! out of this module.

use std::sync::Arc;

/// Physical key code as sent by the compositor over `wl_keyboard.key`.
///
/// The numeric value is the raw Linux evdev scancode (e.g.
/// `KEY_ESC = 1`, `KEY_BACKSPACE = 14`, `KEY_TAB = 15`, `KEY_ENTER = 28`).
/// wayr adds the +8 X11 offset internally before handing the keycode
/// to xkbcommon, but the value surfaced to consumers is the evdev
/// scancode — direct from the wire — so consumers can match against
/// `linux/input-event-codes.h` constants without a translation step.
/// `wayr` does not translate these to character text directly —
/// that's [`KeyEvent::text`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ScanCode(pub u32);

/// Logical key identification, derived from the keymap + scancode +
/// modifier state.
///
/// Stable across keyboard layouts in the sense of "the key that types
/// `a` on a US layout types the same character regardless of which
/// physical key the user's layout maps it to" — useful for shortcuts.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum KeyCode {
    /// A character key. The string is the key's symbolic name as
    /// xkbcommon emits it (e.g. `"a"`, `"A"`, `"Return"`, `"F1"`).
    Named(String),

    /// A keysym `wayr` doesn't have a named variant for. The numeric
    /// value is the xkbcommon keysym constant.
    Sym(u32),
}

/// Modifier state at the moment a key event was generated.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash)]
pub struct Modifiers {
    /// Shift held.
    pub shift: bool,
    /// Ctrl held.
    pub ctrl: bool,
    /// Alt held (Mod1 in X11 / xkbcommon terms).
    pub alt: bool,
    /// Super / Mod4 held (typically the "Windows" / "Cmd" key).
    pub logo: bool,
    /// Caps lock active.
    pub caps_lock: bool,
    /// Num lock active.
    pub num_lock: bool,
}

/// Whether a key was just pressed or released.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum KeyState {
    /// Key transitioned to "pressed". Synthetic repeat events also
    /// carry `Pressed`.
    Pressed,
    /// Key transitioned to "released".
    Released,
}

/// A single keyboard event.
///
/// Carries both the raw scancode (for low-level shortcut detection)
/// and the xkbcommon-translated text (for typing). Consumers typically
/// use `text` for character input fields and `key_code` + `modifiers`
/// for command bindings.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub struct KeyEvent {
    /// Physical scancode.
    pub scancode: ScanCode,
    /// Logical key (after layout translation).
    pub key_code: KeyCode,
    /// Modifier state at the time of the event.
    pub modifiers: Modifiers,
    /// Press or release.
    pub state: KeyState,
    /// UTF-8 text the key produces with current modifier state. `None`
    /// for non-character keys (Enter, F1, arrows, BackSpace, Escape,
    /// Tab, Delete — wayr filters single ASCII control characters out
    /// of `text` since they pair with a [`KeyCode::Named`] keysym
    /// name and the named path is the canonical way to handle them).
    /// `Some("")` never occurs — wayr maps the empty UTF-8 case to
    /// `None`. Multi-codepoint values can arise from dead-key
    /// composition where the same physical key produces e.g. `"â"`
    /// (one scalar) or `"ä"` (combining sequence).
    pub text: Option<String>,
    /// `true` if this event was generated by the key-repeat timer
    /// rather than a fresh physical press.
    pub repeat: bool,
}

/// Configured key-repeat behaviour, reported by the compositor.
///
/// `wayr` drives repeat events internally using a calloop timer so
/// consumers don't have to. This is exposed for diagnostics + for
/// consumers that want to disable repeat for a specific surface.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct RepeatInfo {
    /// Delay before repeat begins, in milliseconds. `0` disables.
    pub delay_ms: u32,
    /// Repeat rate, in keys per second. `0` disables.
    pub rate_per_sec: u32,
}

/// Reference-counted keymap handle, valid as long as `wayr` holds it.
///
/// Opaque to consumers in v0.1; provided so advanced consumers can
/// implement custom IME / shortcut systems against the same keymap
/// `wayr` is using internally. Concrete type lands with #10.
#[derive(Clone)]
pub struct Keymap(pub(crate) Arc<()>);

impl std::fmt::Debug for Keymap {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Keymap").finish_non_exhaustive()
    }
}
